packages:
  esp8266:esp8266:
    url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
  esp32:esp32:
    url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

platforms:
  esp32:
    board: esp32:esp32:featheresp32:FlashFreq=80
    package: esp32:esp32
    gcc:
      features:
      defines:
        - ESP32
        - ARDUINO_ARCH_ESP32
        - ARDUINO_FEATHER_ESP32
        - NUM_SERIAL_PORTS=3
      warnings:
      flags:
  esp8266:
    board: esp8266:esp8266:huzzah:eesz=4M3M,xtal=80
    package: esp8266:esp8266
    gcc:
      features:
      defines:
        - ESP8266
        - ARDUINO_ARCH_ESP8266
        - ARDUINO_ESP8266_ESP12
        - NUM_SERIAL_PORTS=2
      warnings:
      flags:

compile:
  platforms:
    - esp32
    - esp8266
